name: Delete PR env

on:
  repository_dispatch:
    types: [delete_env]

jobs:
  delete_env:
    runs-on: ubuntu-20.04
    defaults:
      run:
        working-directory: event-website
    steps:
      - uses: actions/checkout@master
      - uses: hashicorp/setup-terraform@v1
      - run: terraform init
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - name: Select event workspace
        run: terraform workspace select ${{ github.event.client_payload.event }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - name: Destroy env
        run: terraform destroy -auto-approve
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
          TF_VAR_cloudflare_token: ${{ secrets.TF_VAR_CLOUDFLARE_TOKEN }}
          TF_VAR_domain: ${{ github.event.client_payload.domain }}
      - name: Switch to default workspace
        run: terraform workspace select default
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
      - name: Delete workspace
        run: terraform workspace delete ${{ github.event.client_payload.event }}
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: eu-central-1
  notify_env_destroyed:
    runs-on: ubuntu-20.04
    needs: delete_env
    steps:
      - name: Find Deploy Comment
        uses: peter-evans/find-comment@v1
        id: find_comment
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.client_payload.pr_number }}
          repository: pythonpizza/${{ github.event.client_payload.repository }}
          comment-author: pythonpizzabot
      - name: Create comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.find_comment.outputs.comment-id == null }}
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.client_payload.pr_number }}
          repository: pythonpizza/${{ github.event.client_payload.repository }}
          body: Environment deleted ❌
      - name: Update comment
        uses: peter-evans/create-or-update-comment@v1
        if: ${{ steps.find_comment.outputs.comment-id != null }}
        with:
          token: ${{ secrets.BOT_TOKEN }}
          issue-number: ${{ github.event.number }}
          edit-mode: replace
          comment-id: ${{ steps.find_comment.outputs.comment-id }}
          repository: pythonpizza/${{ github.event.client_payload.repository }}
          body: Environment deleted ❌
