name: Deploy

on:
  repository_dispatch:
    types: [prod_push]

jobs:
  build-site:
    - uses: actions/checkout@master
      with:
        repository: "pythonpizza/${{ github.event.client_payload.repository }}"
        token: ${{ secrets.BOT_TOKEN }}
    - uses: actions/setup-node@v2
      with:
        node-version: "15.5.1"
    - name: Install dependencies
      run: yarn
    - name: Build site
      run: yarn build
