name: Deploy

on:
  repository_dispatch:
    types: [prod_push]

jobs:
  build-site:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@master
        with:
          repository: "pythonpizza/${{ github.event.client_payload.repository }}"
          token: ${{ secrets.BOT_TOKEN }}
      - uses: actions/setup-node@v2
        with:
          node-version: "15.5.1"
      - name: Install dependencies
        run: yarn
      - name: Build site
        run: yarn build
      - name: Upload to S3
        run: |
          set +e
          AW=$(aws s3 cp ./out/ s3://${{ github.event.client_payload.event }}.python.pizza/ --recursive)
          echo $AW
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
